extends:
  - airbnb

  - prettier/flowtype
  - prettier/react
  - plugin:flowtype/recommended
  - prettier

plugins:
  - prettier
  - flowtype

parser: babel-eslint

rules:
  prettier/prettier:
    - error

env:
  browser: true
  node: true
